// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Providers from "./provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "CreateOs",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//           <body
//             className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//           >
//                   <Providers>{children}</Providers>
//           </body>
//     </html>
//   );
// }

import { ThemeProvider } from './context/themeContext';
import './globals.css';
import MainNav from './components/general/navbar';
import Providers from './provider';
export const metadata = {
  title: 'CreateOs',
  description: 'Your app description',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var saved = localStorage.getItem('theme');
                  var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  if (saved === 'dark' || (!saved && prefersDark)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body>
        <Providers>
          <MainNav/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
